[package]
name = "checkers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ellipsoid = "0.3.1"
rand = "0.8.5"
async-std = "1.1"
strum = {version = "0.24", features=["derive"]}